# Site settings
title: Jakub Wiśniewski
email: jwisniewski.cg@gmail.com
url: https://badbadsloth.github.io
description: "Freelance concept artist and illustrator working in Warsaw, Poland."
# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://instagram.com/kubawisniewsky
  - title: behance
    url: https://www.behance.net/jwisniewsky
  - title: deviantart
    url: http://badbaddog.deviantart.com/
  - title: facebook
    url: http://facebook.com/kuba.draws
  - title: twitch
    url: https://www.twitch.tv/badbaddog

# Build settings
markdown: kramdown
permalink: pretty
